//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::channels::Entity as Channels;
pub use super::confession_guild_hashes::Entity as ConfessionGuildHashes;
pub use super::guild::Entity as Guild;
